export {
  ATTACK_CATALOG_VERSION,
  ATTACK_TACTICS,
  ATTACK_TECHNIQUES,
} from '../../electron/contracts/tasks';
export type {
  AttackTacticId,
  TaskStatus,
  SuccessCriterion,
  PentestTask,
  PentestTaskInput,
  PttParseResult,
  TacticProgress,
  TaskContextPackage,
  TaskNodeKind,
  PentestObjective,
  ExecutionStep,
  TaskStepInput,
  TaskStepPlanInput,
  TaskPlanGroupInput,
  TaskTraceSource,
  TaskTraceStatus,
  TaskTraceEntry,
  TaskTracePackage,
} from '../../electron/contracts/tasks';
