import { describe, expect, it } from 'vitest';
import { buildSystemInstructions } from '@electron/services/agent-system-instructions';

describe('Agent system instructions', () => {
  it('separates managed evidence, knowledge, vulnerabilities, and reports', () => {
    const instructions = buildSystemInstructions();
    expect(instructions).toContain('Hexestra-managed tools are the only supported write path');
    expect(instructions).toContain('report_upsert');
    expect(instructions).toContain('Never create');
    expect(instructions).toContain('findings/, vulnerabilities/, evidence/, or');
    expect(instructions).toContain('reports/, even if an older project Skill');
    expect(instructions).toMatch(/project Skill\s+"hexestra-records"/);
    expect(instructions).toContain('It owns Evidence/Finding/Vulnerability');
    expect(instructions).toContain('corresponding list');
    expect(instructions).toContain('call report_list before');
    expect(instructions).toContain('claiming a report was saved');
    expect(instructions).toMatch(/project Skill\s+"hexestra-report"/);
    expect(instructions).toContain('Use attack_catalog_list');
    expect(instructions).toContain('attack_catalog_search');
    expect(instructions).toContain('Never invent, approximate, or silently substitute an ATT&CK ID');
    expect(instructions).toContain('Focus persists for the active conversation');
    expect(instructions).toContain('do not call task_focus again');
    expect(instructions).toContain('It owns report structure');
    expect(instructions).toContain('semantic labels from the operator\'s');
    expect(instructions).toContain('call scope_update');
    expect(instructions).toContain('Register confirmed\nassets in evidence order with asset_register');
    expect(instructions).toContain('submit them together in the assets array');
    expect(instructions).toContain('verify with\nasset_get');
    expect(instructions).toMatch(/before continuing the scan/);
    expect(instructions).toContain('asset_relation_upsert');
    expect(instructions).toContain('Never label\nunrelated third-party');
    expect(instructions).toContain('hexestra_dynamic_context');
    expect(instructions).toContain('dynamic System context');
    expect(instructions).toContain('not\npart of the operator\'s message history');
    expect(instructions).not.toContain('hexestra_project_knowledge');
    expect(instructions).not.toContain('hexestra_focused_task_context');
    expect(instructions).toMatch(/shared by every chat conversation/);
    expect(instructions).toMatch(/Call target_list, task_list, finding_list,\s+vulnerability_list, evidence_list/);
    expect(instructions).toContain('"hexestra-pentest" for penetration-testing orchestration');
    expect(instructions).toContain('Never invoke or');
    expect(instructions).toContain('personal/user skill named "pentest"');
    expect(instructions).toContain('Use shell_profiles and shell_sessions');
    expect(instructions).toContain('{{command_base64}}');
    expect(instructions).toContain('commandMode=auto probes direct OS-command input and then PHP eval input');
    expect(instructions).toContain('commandMode=php_eval with {{command}}');
    expect(instructions).toContain('echoing the encoded request body');
    expect(instructions).toContain('encoded request body');
    expect(instructions).toContain('does not\nproduce valid command markers');
    expect(instructions).toContain('Infrastructure SSH profiles are jump routes');
    expect(instructions).toContain('shell_save_evidence when a command transcript');
    expect(instructions).not.toContain('plaintext project audit');
    expect(instructions).toContain('bypass reverse-');
  });
});
